FROM node:20.11.1-bookworm-slim AS base
WORKDIR /src/backend
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn
COPY . .

FROM base as builder
WORKDIR /src/backend
RUN yarn build

FROM node:20.11.1-bookworm-slim
WORKDIR /src/backend
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install --prod
COPY --from=builder src/backend/dist ./
EXPOSE 5000

ENTRYPOINT ["sh", "-c", "yarn migrate && node index.js"]
